CREATE DATABASE `testrest` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `testrest`;

CREATE TABLE IF NOT EXISTS `users` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`name` VARCHAR(250) NOT NULL,
`password_hash` VARCHAR(250) NOT NULL,
`salt` VARCHAR(250) NOT NULL,
`session_id` VARCHAR(250) NULL,
`auth_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;